"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[](bg:color_bg2 fg:color_bg1)\
$directory\
[](bg:color_bg3 fg:color_bg2)\
$git_branch\
$git_status\
$git_metrics\
[](bg:none fg:color_bg3)\
$fill\
[](bg:none fg:color_bg3)\
$package\
[](bg:color_bg3 fg:color_bg2)\
$rust\
$python\
$conda\
[](bg:color_bg2 fg:color_bg1)\
$cmd_duration\
$hostname
$character
"""

palette = "gruvbox_material"

[palettes.gruvbox_material]
color_fg1 = "#ddc7a1"
color_bg1 = "#282828"
color_bg2 = "#3c3836"
color_bg3 = "#504945"
color_blue = "#7daea3"
color_green = "#a9b665"
color_red = "#ea6962"

[os]
disabled = false
style = "bg:color_bg1 fg:color_fg1"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
style_user = "bg:color_bg1 fg:color_fg1"
style_root = "bg:color_bg1 fg:color_red"
format = "[ $user in ]($style)"

[directory]
read_only = "  "
style = "bold bg:color_bg2 fg:color_fg1"
read_only_style = "bg:color_bg2 fg:color_red"
format = "[$read_only]($read_only_style)[  $path]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:color_bg3 fg:color_fg1"
format = "[ on $symbol $branch ]($style)"

[git_status]
style = "bg:color_bg3 fg:color_blue"
format = "[($all_status$ahead_behind )]($style)"

[git_metrics]
disabled = false
added_style = "bg:color_bg3 fg:color_green"
deleted_style = "bg:color_bg3 fg:color_red"
format = "([+$added ]($added_style))([-$deleted ]($deleted_style))"

[fill]
symbol = " "

[package]
symbol = ""
style = "bg:color_bg3 fg:color_blue"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "bg:color_bg2 fg:color_green"
format = "[ $symbol $version ]($style)"

[python]
symbol = ""
style = "bg:color_bg2 fg:color_green"
format = "[ $symbol $version ]($style)"

[conda]
symbol = ""
style = "bg:color_bg2 fg:color_green"
format = "[ $symbol $environment ]($style)"

[cmd_duration]
style = "bg:color_bg1 fg:color_fg1"
format = "[  $duration ]($style)"

[hostname]
ssh_only = true
ssh_symbol = "󰖟 "
style = "bg:color_bg1 color_fg1"
format = "[$ssh_symbol$hostname ]($style)"
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
