return {
  kind = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "﬌",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "ﬦ",
    TypeParameter = "",
  },
  ui = {
    Caret = " ",
    File = " ",
    Files = " ",
    Gear = " ",
    History = " ",
    NewFile = " ",
    Project = " ",
    SignOut = " ",
    Telescope = " ",
    Text = " ",
  },
  diagnostics = {
    Error = "",
    Warn = "",
    Hint = "",
    Info = "",
  }
}
